Repository tableau/server-client-python, pull requests merged in 2021-11, with the labels that each got.

#804 Type hinting on Datasources and Workbooks
  .github/workflows/run-tests.yml
  setup.cfg
  setup.py
  tableauserverclient/_version.py
  tableauserverclient/exponential_backoff.py
  tableauserverclient/models/database_item.py
  tableauserverclient/models/datasource_item.py
  tableauserverclient/models/dqw_item.py
  tableauserverclient/models/job_item.py
  tableauserverclient/models/project_item.py
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/endpoint/datasources_endpoint.py
  tableauserverclient/server/endpoint/endpoint.py
  tableauserverclient/server/endpoint/exceptions.py
  tableauserverclient/server/endpoint/jobs_endpoint.py
  tableauserverclient/server/endpoint/workbooks_endpoint.py
  tableauserverclient/server/request_factory.py
  tableauserverclient/server/server.py
  test/test_datasource.py
  test/test_regression_tests.py
  test/test_workbook.py
Labels: CLAApproved

#946 Fix slack once and for all
  .github/workflows/slack.yml
Labels: cla:signed

#948 Update workflows
  .github/workflows/run-tests.yml
  .github/workflows/slack.yml
Labels: cla:signed

#928 Added missing params from workbooks.publish() documentation
  docs/api-ref.md
Labels: docs, cla:signed

#939 Type hint Job
  .github/workflows/slack.yml
  tableauserverclient/models/job_item.py
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/endpoint/jobs_endpoint.py
  test/test_job.py
Labels: cla:signed

#528 Project Permission & Default Permission Docs
  docs/api-ref.md
Labels: CLAApproved, docs

#617 Clean up hidden_views by making it an attribute of WorkbookItem
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/endpoint/workbooks_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_workbook.py
Labels: CLAApproved, cla:missing

#931 Add support to datasource and workbook revisions
  tableauserverclient/__init__.py
  tableauserverclient/models/__init__.py
  tableauserverclient/models/datasource_item.py
  tableauserverclient/models/revision_item.py
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/__init__.py
  tableauserverclient/server/endpoint/datasources_endpoint.py
  tableauserverclient/server/endpoint/workbooks_endpoint.py
Labels: cla:signed

#956 Jorwoods/type hint revisions
  tableauserverclient/models/datasource_item.py
  tableauserverclient/models/revision_item.py
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/endpoint/datasources_endpoint.py
  tableauserverclient/server/endpoint/workbooks_endpoint.py
  test/assets/datasource_revision.xml
  test/assets/workbook_revision.xml
  test/test_datasource.py
  test/test_workbook.py
Labels: cla:signed
