Repository tableau/server-client-python, pull requests merged in 2022-01, with the labels that each got.

#971 Update api-ref.md
  docs/api-ref.md
Labels: cla:missing

#977 change distutils to packaging
  tableauserverclient/server/endpoint/endpoint.py
Labels: cla:signed

#934 Jorwoods/type hint data alert
  tableauserverclient/models/data_alert_item.py
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/endpoint/data_alert_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_dataalert.py
Labels: cla:signed

#936 Jorwoods/type hint favorites
  tableauserverclient/models/favorites_item.py
  tableauserverclient/server/endpoint/favorites_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_favorites.py
Labels: cla:signed

#937 Jorwoods/type hint flows
  tableauserverclient/models/flow_item.py
  tableauserverclient/server/endpoint/flows_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_flow.py
Labels: cla:signed

#969 Add type hints for schedules
  tableauserverclient/models/interval_item.py
  tableauserverclient/models/schedule_item.py
  tableauserverclient/server/endpoint/schedules_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_schedule.py
Labels: cla:signed

#938 Jorwoods/type hint groups
  tableauserverclient/models/group_item.py
  tableauserverclient/server/endpoint/groups_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_group.py
Labels: cla:signed

#940 Jorwoods/type hint permissions
  tableauserverclient/models/permissions_item.py
  tableauserverclient/server/endpoint/default_permissions_endpoint.py
  tableauserverclient/server/endpoint/permissions_endpoint.py
  tableauserverclient/server/request_factory.py
Labels: cla:signed

#941 Jorwoods/type hint projects
  tableauserverclient/models/project_item.py
  tableauserverclient/server/endpoint/projects_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_group.py
  test/test_project.py
Labels: cla:signed

#950 Jorwoods/type hint flow runs
  tableauserverclient/models/flow_run_item.py
  tableauserverclient/server/endpoint/flow_runs_endpoint.py
  test/test_flowruns.py
Labels: cla:signed

#942 Type hint site
  tableauserverclient/models/site_item.py
  tableauserverclient/server/endpoint/sites_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_site.py
Labels: cla:signed

#943 Type hint subscriptions
  tableauserverclient/models/subscription_item.py
  tableauserverclient/server/endpoint/subscriptions_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_subscription.py
Labels: cla:signed

#944 Jorwoods/type hint user
  tableauserverclient/models/user_item.py
  tableauserverclient/server/endpoint/users_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_user.py
Labels: cla:signed

#945 Type hint webhooks
  tableauserverclient/models/webhook_item.py
  tableauserverclient/server/endpoint/webhooks_endpoint.py
  tableauserverclient/server/endpoint/workbooks_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_schedule.py
  test/test_webhook.py
Labels: cla:signed

#949 Type hint views
  tableauserverclient/models/view_item.py
  tableauserverclient/server/endpoint/views_endpoint.py
  test/test_project.py
  test/test_view.py
Labels: cla:signed

#925 Accept `None` as parameter for the `site_id` of `TableauAuth` and `PersonalAccessTokenAuth`
  tableauserverclient/models/personal_access_token_auth.py
  tableauserverclient/models/tableau_auth.py
Labels: CLAApproved

#982 Fix typings for clean run in mypy
  tableauserverclient/models/pagination_item.py
  tableauserverclient/models/permissions_item.py
  tableauserverclient/server/endpoint/groups_endpoint.py
  test/test_group.py
  test/test_project.py
Labels: bug, fixed
