Repository tableau/server-client-python, pull requests merged in 2024-02, with the labels that each got.

#1357 feat: add description support on wb publish
  tableauserverclient/models/workbook_item.py
  tableauserverclient/server/request_factory.py
  test/assets/workbook_publish.xml
  test/test_workbook.py
Labels: cla:signed

#1355 Add support for daily (24 hour) intervals for tasks
  tableauserverclient/models/interval_item.py
  test/assets/tasks_with_interval.xml
  test/test_task.py
Labels: cla:missing

#1356 Update Actions to include Python 3.12 and reduce duplicate test runs
  .github/workflows/run-tests.yml
Labels: infra, cla:signed
