Repository tableau/server-client-python, pull requests merged in 2024-09, with the labels that each got.

#1447 chore: typing decorators
  tableauserverclient/server/endpoint/datasources_endpoint.py
  tableauserverclient/server/endpoint/endpoint.py
  tableauserverclient/server/endpoint/flows_endpoint.py
  tableauserverclient/server/endpoint/jobs_endpoint.py
  tableauserverclient/server/endpoint/resource_tagger.py
  tableauserverclient/server/endpoint/tables_endpoint.py
  tableauserverclient/server/endpoint/views_endpoint.py
  tableauserverclient/server/endpoint/workbooks_endpoint.py
  tableauserverclient/server/request_factory.py
  test/test_tagging.py
Labels: cla:signed

#1449 fix: Pager typing
  tableauserverclient/server/pager.py
  test/test_pager.py
Labels: cla:signed

#1448 fix: JobItem repr
  tableauserverclient/models/job_item.py
  tableauserverclient/server/endpoint/jobs_endpoint.py
  test/test_job.py
Labels: cla:signed

#1452 docs: clarify django style filters
  docs/filter-sort.md
Labels: cla:signed

#1453 docs: environment variables supported by v0.33
  docs/environment-variables.md
Labels: cla:signed, 0.33

#1455 chore(typing): include samples in type checks
  pyproject.toml
  samples/explore_favorites.py
  samples/list.py
  tableauserverclient/models/favorites_item.py
Labels: cla:signed

#1460 fix: queryset support for flowruns
  tableauserverclient/server/endpoint/flow_runs_endpoint.py
  tableauserverclient/server/query.py
  test/_utils.py
  test/assets/flow_runs_get.xml
  test/test_flowruns.py
Labels: cla:signed

#1471 #1464 - docs update for filtering on boolean values
  tableauserverclient/server/request_options.py
Labels: docs

#1477 chore(versions): update remaining f-strings
  tableauserverclient/_version.py
  tableauserverclient/server/endpoint/endpoint.py
  test/test_schedule.py
Labels: cla:signed
